---
title: "Otros"
output:
  html_document:
    includes:
      in_header: Logo.html
---

```{=html}
<style>
 .html-widget {
     margin: auto;
 }
 </style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
pacman::p_load(terra, 
               sf, 
               fs, 
               hablar, 
               gcookbook, 
               plotly, 
               extrafont, 
               RColorBrewer, 
               rmapshaper, 
               readxl, 
               glue, 
               hrbrthemes, 
               tidyverse, 
               leaflet, 
               htmltools, 
               leaflet.extras)
```

------------------------------------------------------------------------

## Tabla ejemplo

Una tabla para demostrar que se pueden subir tablas.

| ID  | Año  | Valor |
|:---:|:----:|:-----:|
|  1  | 1965 | 32.8  |
|  2  | 1966 | 45.2  |
|  3  | 1967 | 25.8  |
|  4  | 1968 | 24.2  |
|  5  | 1969 | 28.6  |
|  6  | 1970 | 21.9  |
|  7  | 1971 | 28.5  |
|  8  | 1972 | 27.8  |
|  9  | 1973 | 28.5  |
| 10  | 1974 | 38.4  |
| 11  | 1975 | 29.9  |

------------------------------------------------------------------------

## Gráfico ejemplo

Este es un gráfico para demostrar que se pueden hacer gráficos.

```{r echo=FALSE, fig.align='center', fig.width=10, out.width='100%'} plot(x=c(1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975),       y=c(31.6,32.8,45.2,25.8,24.2,28.6,21.9,28.5,27.8,28.5,37.4,29.9),      type = "o",       ylab = "Precipitación máxima anual (mm)",       xlab = "Años",       main = "Gráfico de prueba",      pch =8) grid()}
```

------------------------------------------------------------------------

## Mapa generado ejemplo

Este es un mapa para demostrar que tan bien salen los mapas

```{r echo=FALSE, fig.align='center', fig.width=10, out.width='100%'} mapa_mundo <- map_data("italy")  mapa_mundo %>%   ggplot() +   geom_polygon(aes( x= long, y = lat, group = group),                fill = "black",                color = "white")+   theme(aspect.ratio = 1)}
```

---

## Histograma del índice de desempeño municipal

La siguiente figura ilustra el histograma, tomando como valor el promedio entre el año 2016 al 2021.

```{r include=FALSE}
tble <- read_csv('tble/mdm_sub.csv')
tble <- mutate(tble, year = paste0('y', year))
tble <- tble %>% spread(year, value)
tble <- mutate(tble, average = apply(as.data.frame(tble)[,8:13], 1, 'mean'))
dbse <- st_read('gpkg/mpio.gpkg', quiet = TRUE)
dbse <- inner_join(dbse, tble, by = c('MPIO_CCNCT' = 'codigompio'))
```

```{r include=TRUE, echo=FALSE}
g_hist <- ggplot(data = tble, aes(x = average)) + 
  geom_histogram(binwidth = 0.4) + 
  theme_ipsum_es() + 
  labs(x = 'Medición de Desempeño Municipal', 
       y = 'Frecuencia (cantidad municipios)') + 
  ggtitle(label = 'Índice del desempeño a nivel municipal (2016-2021)') + 
  scale_x_continuous(limits = c(0, 100)) +
  theme_ipsum_ps() + 
  theme()
```

```{r echo=FALSE, warning=FALSE, fig.align='center', out.width='100%', fig.width=12}
g_hist
```

------------------------------------------------------------------------

## Mapa del índice de desempeño a nivel municipal

El comportamiento a nivel espacial de estos datos se ilustra en el siguiente interactivo.

```{r echo=FALSE, warning=FALSE, out.width='100%', fig.width=12}
cnmr <- colorNumeric(palette = 'inferno', domain = dbse$y2016, n = 9)

leaflet() %>% 
  addProviderTiles(provider = 'Esri.WorldImagery') %>% 
  addPolygons(data = dbse, 
              fillColor = ~cnmr(dbse$y2016), 
              popup = paste0(dbse$MPIO_CNMBR, ' - ', dbse$y2016),
              color = 'white', weight = 0.4, fillOpacity = 0.9, 
              smoothFactor = 0.5) %>% 
  addLegend(position = 'bottomright', 
            values = dbse$y2016, 
            pal = cnmr, 
            title = 'MDM', 
            opacity = 1,
            labFormat = labelFormat(transform = function(x) 
              sort(x,decreasing = TRUE))) %>% 
  addSearchOSM() %>% 
  addScaleBar(position = "topright",
              options = scaleBarOptions(maxWidth = 100, 
                                        metric = TRUE, 
                                        imperial = TRUE, 
                                        updateWhenIdle = TRUE)) %>% 
  addResetMapButton() %>% 
  addMiniMap(position = "bottomleft")
```

------------------------------------------------------------------------

## Gráfico dinámico

Ahora bien revisemos el comportamiento de las 3 principales ciudades del país en el tiempo, entre 2016 y 2021.

```{r echo=FALSE, warning=FALSE}
main <- tble %>% 
  filter(mpio %in% c('Cali', 'Medellín', 'Bogotá')) %>% 
  dplyr::select(mpio, y2016:y2021) %>% 
  gather(var, value, -mpio) %>%
  mutate(year = parse_number(var))

g_lne <- ggplot(data = main, aes(x = year, y = value, col = mpio)) + 
  # geom_line(group = 1) +
  # geom_point() +
  geom_smooth(se = FALSE, method = 'loess') + 
  ggtitle('Comportamiento anual entre 2016 y el 2021 para el MDD') +
  labs(x = 'Año', y = 'Índice de desempeño municipal', col = 'Municipio') +
  theme(legend.position = 'bottom', 
        plot.title = element_text(face = 'bold', hjust = 0.5))
```

```{r echo=FALSE, message=FALSE, warning=FALSE, out.width='100%', fig.width=12}
ggplotly(g_lne)
```
